# Generated by Django 3.1.5 on 2021-01-28 23:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
    ]
